### ISSUE TITLE
CI: Docker Build and Wine Test

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337#417]
```
name: Docker Build and Wine Test

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/wine-docker:latest
        build-args: |
          WINE_VERSION=stable

  run-wine:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/wine-docker:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check Wine version
      run: wine --version
```
